import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

// Initialize the secure master access client
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
  }
);

export async function POST(req: NextRequest) {
  try {
    // 1. Parse inbound multipart/form-data payload generated by your email parser service
    const emailFormData = await req.formData();
    
    // Core email headers extracted by the parser service router
    const senderEmail = emailFormData.get('from') as string;  // e.g., "billing@apexpiping.com" or a foreman forwarding an email
    const emailSubject = emailFormData.get('subject') as string || 'Automated Email Intake Asset';
    const attachmentFile = emailFormData.get('attachment') as File | null; // The invoice or PO PDF file object

    if (!senderEmail) {
      return NextResponse.json({ error: 'Bad Request: Missing originating sender headers.' }, { status: 400 });
    }

    if (!attachmentFile) {
      return NextResponse.json({ error: 'Ignored: No valid file attachments found in email stream payload.' }, { status: 200 });
    }

    // 2. Identify the active project space based on the sender's domain or a customized forwarding routing token
    // For production scaling, we map vendor configurations or check which user profile has registered this specific vendor domain
    const { data: projectMapping, error: mappingErr } = await supabase
      .from('vendor_project_assignments')
      .select('project_id, user_id, projects(project_name)')
      .eq('vendor_email_domain', senderEmail.split('@')[1]) 
      .limit(1)
      .single();

    if (mappingErr || !projectMapping) {
      console.warn(`[INTAKE BYPASS] Received email invoice from unmapped origin: ${senderEmail}`);
      return NextResponse.json({ 
        message: 'Intake Ignored: Senders email domain is not mapped to an active project monitoring workspace ledger.' 
      }, { status: 200 });
    }

    const projectId = projectMapping.project_id;
    const userId = projectMapping.user_id;
    const projectName = (projectMapping as any).projects?.project_name || 'Active Jobsite';

    // 3. Process the file stream buffer into a Base64 text string for OpenAI Vision/Text parsing compatibility
    const fileBytesBuffer = await attachmentFile.arrayBuffer();
    const base64AttachmentPayload = Buffer.from(fileBytesBuffer).toString('base64');

    // 4. Securely dispatch the payload to your existing primary core forensic audit endpoint
    const primaryAuditEndpoint = `${req.nextUrl.origin}/api/audit`;
    
    // Trigger the analysis engine in a non-blocking background process to avoid timing out the inbound email server
    fetch(primaryAuditEndpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        userId: userId,
        projectId: projectId,
        invoiceName: `Email_Intake_${Date.now()}_${attachmentFile.name.replace(/\s+/g, '_')}`,
        invoiceFileBase64: base64AttachmentPayload,
        vendorEmail: senderEmail,
      }),
    }).catch((bgError) => {
      console.error('CRITICAL: Background execution pipeline exception on email intake:', bgError);
    });

    // 5. Respond with a 200 OK block to clear the email parsing provider queue
    return NextResponse.json({
      success: true,
      message: `Email asset intercepted successfully. Routed internally to project workspace: ${projectName}`,
    }, { status: 200 });

  } catch (error: any) {
    console.error('CRITICAL EXCEPTION IN EMAIL INTAKE CONTROLLER:', error);
    return NextResponse.json(
      { error: 'Internal Processing Engine Error', message: error.message || 'Unexpected anomaly.' },
      { status: 500 }
    );
  }
}
